### Get book
GET localhost:8080/books/get?id=1

### Create user
POST localhost:8080/users/create
Content-Type: application/x-www-form-urlencoded

login={{$random.alphabetic(5)}}&email={{$random.integer(10)}}&password={{$random.integer(10)}}

### Update book
POST localhost:8080/books/update
Content-Type: application/x-www-form-urlencoded

id=1&title=Abc2&rating=8

### Delete book
POST localhost:8080/books/delete
Content-Type: application/x-www-form-urlencoded

id=1
### Get all users
GET localhost:8080/users/list

### Get all by rating
GET localhost:8080/books/byRating?rating=7

### Get all with publisher
GET localhost:8080/books/withPublisher

### Get all by publisher
GET localhost:8080/books/byPublisher?publisherId=1

### Get all by author
GET localhost:8080/books/byAuthor?authorId=2